name: Java CI

on: [push]

jobs:
  build_java:
    name: Build java part
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Release artifact
        uses: actions/upload-artifact@v1
        with:
          name: G-Earth-${{ matrix.os }}
          path: G-Earth/target/bin/G-Earth.jar

  build_rust:
    name: Build rust part
    needs: build_java
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ubuntu-latest, windows-latest]
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: G-Mem
          - name: windows
            os: windows-latest
            artifact_name: G-Mem.exe
    steps:
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: build
          args: --release --manifest-path=G-Mem/Cargo.toml

      - name: Release artifact
        uses: actions/upload-artifact@v1
        with:
          name: G-Earth-${{ matrix.os }}
          path: G-Mem/target/release/${{ matrix.artifact_name }}